name: Docs

on:
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install docs dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install pandoc \
            python3-gdal python3-sphinx python3-sphinxcontrib.spelling \
            python3-cartopy python3-ipython python3-nbsphinx \
            python3-sphinx-rtd-theme
          python -m pip install .[all]

      - name: Build docs
        run: |
          mkdir -p _static
          python3 -m sphinx -W -b html . _build/html
        working-directory: docs

      - name: Check links
        run: |
          mkdir -p _static
          python3 -m sphinx -W -b linkcheck . _build/linkcheck
        working-directory: docs

      - name: Doctest
        run: |
          mkdir -p _static
          python3 -m sphinx -W -b doctest . _build/doctest
        working-directory: docs

      - name: Spellcheck
        run: |
          mkdir -p _static
          python3 -m sphinx -W -b spelling . _build/spelling
        working-directory: docs
