name: Lint

on:
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

env:
  PACKAGE: s1etad

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install lint dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pydocstyle isort black
          if [ -f requirements-lint.txt ]; then pip install -r requirements-lint.txt; fi

      - name: Lint (flake8)
        run: |
          python -m flake8 --count --show-source --statistics ${PACKAGE}

      - name: Lint (pydocstyle)
        run: |
          python -m pydocstyle --count ${PACKAGE}

      - name: Lint (isort)
        run: |
          python -m isort --check ${PACKAGE}

      - name: Lint (black)
        run: |
          python -m black --check ${PACKAGE}

